[workspace]
members = [
  # Packages
  "packages/network_integration",
  "packages/shade_protocol",
  "packages/secretcli",

  # Network setups
  "contracts/initializer",
  "contracts/airdrop",

  # Protocol contracts
  "contracts/governance",
  "contracts/staking",
  "contracts/mint",
  "contracts/micro_mint",
  "contracts/treasury",
  "contracts/oracle",
  "contracts/snip20",
  "contracts/scrt_staking",

  # Mock contracts
  "contracts/mock_band",
]
