[workspace]
members = [
  "packages/shade_protocol",
  "packages/secretcli",
  "contracts/airdrop",
  "contracts/initializer",
  "contracts/mint",
  "contracts/micro_mint",
  "contracts/treasury",
  "contracts/oracle",
  "contracts/snip20",
  "contracts/mock_band",
]
