[package]
name = "shade-multi-test"
version = "0.1.0"
authors = [
   "hoomp <flammable.shower939@anonaddy.me>"
]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
# mint = ["dep:mint"]
# oracle = ["dep:oracle"]
# mock_band= ["dep:mock_band"]
# governance = ["dep:governance"]
# snip20_staking = ["dep:spip_stkd_0"]
# scrt_staking = ["dep:scrt_staking"]
snip20 = ["dep:snip20"]
# bonds = ["dep:bonds"]
# query_auth = ["dep:query_auth"]
# admin = ["dep:admin"]
# treasury = ["dep:treasury"]
# treasury_manager = ["dep:treasury_manager"]
# shade-oracles = ["dep:shade-oracles"]

[dependencies]
anyhow = { version = "1" }
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" }
shade-protocol = { version = "0.1.0", path = "../shade_protocol", features = ["multi-test"]}
# mint = { version = "0.1.0", path = "../../contracts/mint", optional = true }
# oracle = { version = "0.1.0", path = "../../contracts/oracle", optional = true }
# mock_band = { version = "0.1.0", path = "../../contracts/mock_band", optional = true }
# governance = { version = "0.1.0", path = "../../contracts/governance", optional = true }
# spip_stkd_0 = { version = "0.1.0", path = "../../contracts/snip20_staking", optional = true }
snip20 = { version = "0.1.0", path = "../../contracts/snip20", optional = true }
# bonds = { version = "0.1.0", path = "../../contracts/bonds", optional = true }
# query_auth = { version = "0.1.0", path = "../../contracts/query_auth", optional = true }
# scrt_staking = { version = "0.1.0", path = "../../contracts/scrt_staking", optional = true }
# treasury = { version = "0.1.0", path = "../../contracts/treasury", optional = true }
# treasury_manager = { version = "0.1.0", path = "../../contracts/treasury_manager", optional = true }
# shade-oracles = { git = "https://github.com/securesecrets/shade-oracle.git", tag = "0.11", optional = true }
# admin = { git = "https://github.com/securesecrets/shadeadmin", tag = "v1.0", optional = true }