[package]
name = "shade-protocol"
version = "0.1.0"
authors = [
  "Guy Garcia <guysebastiangarcia@gmail.com>",
  "Jackson Swenson <jacksonswenson22@gmail.com>",
]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["utils"]
# Templates
dex = ["utils", "math", "snip20", "mint", "secretswap", "sienna", "band"]
band = []
secretswap = ["utils"]
sienna = ["utils", "math"]
snip20 = ["utils"]

# Utils
utils = []
errors = []
flexible_msg = []
math = []
storage = []

# Protocol contracts
airdrop = ["utils", "errors"]
initializer = ["snip20", "utils"]
governance = ["utils", "flexible_msg"]
mint = ["utils", "snip20"]
mint_router = ["utils", "snip20"]
oracle = ["snip20"]
scrt_staking = ["utils"]
shd_staking = ["utils"]
treasury = ["utils"]

# Protocol Implementation Contracts
# Used in internal smart contracts
governance-impl = ["governance", "storage"]

# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
debug-print = ["cosmwasm-std/debug-print"]

[dependencies]
cosmwasm-std = { version = "0.10", package = "secret-cosmwasm-std" }
cosmwasm-storage = { version = "0.10", package = "secret-cosmwasm-storage" }
cosmwasm-math-compat = { path = "../cosmwasm_math_compat" }
cosmwasm-schema = "0.10.1"
secret-toolkit = { version = "0.2" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }
# Needed for airdrop
rs_merkle = { git = "https://github.com/FloppyDisck/rs-merkle", branch = "node_export" }
# Needed for transactions
query-authentication = { git = "https://github.com/securesecrets/query-authentication", tag = "v1.2.0" }
remain = "0.2.2"
