[package]
name = "shade-protocol"
version = "0.1.0"
authors = [
  "Guy Garcia <guysebastiangarcia@gmail.com>",
  "Jackson Swenson <jacksonswenson22@gmail.com>",
  "Kyle Wahlberg <kyle.s.wahlberg@gmail.com>"
]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["utils"]

# TODO: Normalize usage, some features are using - while others use _

# Templates
dex = ["utils", "math", "snip20", "mint", "band"]
band = []
secretswap = ["utils"]
sienna = ["utils", "math"]

# Utils
utils = []
errors = []
flexible_msg = []
math = []
storage = []
storage_plus = ["storage", "dep:secret-storage-plus"]
query_auth_lib = ["dep:query-authentication"]
ensemble = ["dep:fadroma"]

# Protocol contracts
airdrop = ["utils", "errors", "dep:remain", "query_auth_lib"]
bonds = ["utils", "errors", "dep:remain", "airdrop", "query_auth_lib", "snip20", "query_auth"]
governance = ["utils", "flexible_msg"]
mint = ["utils", "snip20"]
mint_router = ["utils", "snip20"]
oracle = ["snip20", "dex"]
scrt_staking= ["utils", "adapter", "treasury"]
treasury = ["utils", "adapter", "snip20"]
treasury_manager = ["adapter"]
rewards_emission = ["adapter"]
lp_shade_swap = []
adapter = []
snip20 = ["utils", "errors", "dep:base64", "query_auth_lib"]
query_auth = ["utils", "query_auth_lib", "dep:remain"]
snip20_staking = ["utils", "storage"]
sky = ["snip20", "utils", "dex"]

# Protocol Implementation Contracts
# Used in internal smart contracts
governance-impl = ["governance", "storage"]
snip20-impl = ["snip20", "storage_plus"]
query_auth_impl = ["query_auth", "storage_plus", "dep:base64"]
sky-impl = ["sky", "storage_plus"]

# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
debug-print = [] # TODO: remove this from all cargo configs

[dependencies]
# Smart contract stuff
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret", features = ["staking"] }
cosmwasm-storage = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret" }
secret-storage-plus = { git = "https://github.com/securesecrets/secret-storage-plus", tag = "v1.0.0", optional = true }
cosmwasm-schema = "0.10.1"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

# Temp libs
secret-toolkit = { version = "0.2", features = ["crypto", "permit"] }

# Testing
fadroma = { branch = "v100", commit = 76867e0, git = "https://github.com/hackbg/fadroma.git", features= ["ensemble", "scrt"], optional = true }


# TODO: fix import
chrono = "0.4.19"
base64 = { version = "0.12.3", optional = true }
# Needed for transactions
query-authentication = {git = "https://github.com/securesecrets/query-authentication", tag = "v1.3.0", optional = true }
remain = { version = "0.2.2", optional = true }
subtle = { version = "2.2.3", default-features = false }
sha2 = { version = "0.9.1", default-features = false }
rand_chacha = { version = "0.2.2", default-features = false }
rand_core = { version = "0.5.1", default-features = false }
